env:
  RCLONECONFIG_DRIVE: "ENCRYPTED[8da5e332bd776e2aed19dfbaa57c86820b7fe6c4f3b185cccf0b13f140222c272127fcb5a520b5372f6eebbe53f0e86c]"
  MANIFEST_URL: "https://github.com/SHRP/manifest.git"
  MANIFEST_BRANCH: "shrp-12.1"
  DEVICE_TREE_URL: "https://github.com/plente00/android_device_sony_bahamut_kddi"
  DEVICE_TREE_BRANCH: "pact11"
  DEVICE_PATH: "device/sony/bahamut_kddi"
  DEVICE_NAME: "bahamut_kddi"
  MAKEFILE_NAME: "twrp_bahamut"
  BUILD_TARGET: "boot"
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'AnGgIt88'
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  sync-recovery_script:
    - mkdir -p ~/.config/rclone
    - echo "$RCLONECONFIG_DRIVE" > ~/.config/rclone/rclone.conf
    - cd $WORKDIR
    - mkdir -p recoverybuild && cd recoverybuild
    - repo init --depth=1 --no-repo-verify -u $MANIFEST_URL -b $MANIFEST_BRANCH -g default,-mips,-darwin,-notdefault
    - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
    - git clone --depth 1 $DEVICE_TREE_URL -b $DEVICE_TREE_BRANCH $DEVICE_PATH
    - git clone --depth 1 https://github.com/baunilla/android_kernel_xiaomi_rosy -b lineage-20.0 kernel/xiaomi/rosy

  build-recovery_script:
    - cd $WORKDIR/recoverybuild
    - export ALLOW_MISSING_DEPENDENCIES=true
    - source build/envsetup.sh
    - lunch ${MAKEFILE_NAME}-eng
    - mka ${BUILD_TARGET}image -j8

  upload-recovery_script:
    - cd $WORKDIR/recoverybuild/out/target/product/$DEVICE_NAME
    - recoveryname=$(ls SHRP*-Unofficial*.zip)
    - recoveryaddons=$(ls SHRP_AddonRescue*.zip)
    - rclone copy --drive-chunk-size 256M --stats 1s $recoveryname NFS:recovery/$DEVICE_NAME/twrp -P
    - rclone copy --drive-chunk-size 256M --stats 1s $recoveryaddons NFS:recovery/$DEVICE_NAME/addons -P
    - echo Download link = https://nfs.projek.workers.dev/0:/recovery/${DEVICE_NAME}/twrp/${recoveryname}
    - echo Addons = https://nfs.projek.workers.dev/0:/recovery/${DEVICE_NAME}/twrp/${recoveryaddons}
